/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import type { EditorThemeClasses } from 'lexical';

import '../../styles/EditorTheme.css';

const editorTheme: EditorThemeClasses = {
  autocomplete: 'EditorTheme-autocomplete',
  blockCursor: 'EditorTheme-blockCursor',
  characterLimit: 'EditorTheme-characterLimit',
  code: 'EditorTheme-code',
  codeHighlight: {
    atrule: 'EditorTheme-tokenAttr',
    attr: 'EditorTheme-tokenAttr',
    boolean: 'EditorTheme-tokenProperty',
    builtin: 'EditorTheme-tokenSelector',
    cdata: 'EditorTheme-tokenComment',
    char: 'EditorTheme-tokenSelector',
    class: 'EditorTheme-tokenFunction',
    'class-name': 'EditorTheme-tokenFunction',
    comment: 'EditorTheme-tokenComment',
    constant: 'EditorTheme-tokenProperty',
    deleted: 'EditorTheme-tokenDeleted',
    doctype: 'EditorTheme-tokenComment',
    entity: 'EditorTheme-tokenOperator',
    function: 'EditorTheme-tokenFunction',
    important: 'EditorTheme-tokenVariable',
    inserted: 'EditorTheme-tokenInserted',
    keyword: 'EditorTheme-tokenAttr',
    namespace: 'EditorTheme-tokenVariable',
    number: 'EditorTheme-tokenProperty',
    operator: 'EditorTheme-tokenOperator',
    prolog: 'EditorTheme-tokenComment',
    property: 'EditorTheme-tokenProperty',
    punctuation: 'EditorTheme-tokenPunctuation',
    regex: 'EditorTheme-tokenVariable',
    selector: 'EditorTheme-tokenSelector',
    string: 'EditorTheme-tokenSelector',
    symbol: 'EditorTheme-tokenProperty',
    tag: 'EditorTheme-tokenProperty',
    unchanged: 'EditorTheme-tokenUnchanged',
    url: 'EditorTheme-tokenOperator',
    variable: 'EditorTheme-tokenVariable',
  },
  embedBlock: {
    base: 'EditorTheme-embedBlock',
    focus: 'EditorTheme-embedBlockFocus',
  },
  hashtag: 'EditorTheme-hashtag',
  heading: {
    h1: 'EditorTheme-h1',
    h2: 'EditorTheme-h2',
    h3: 'EditorTheme-h3',
    h4: 'EditorTheme-h4',
    h5: 'EditorTheme-h5',
    h6: 'EditorTheme-h6',
  },
  hr: 'EditorTheme-hr',
  hrSelected: 'EditorTheme-hrSelected',
  image: 'editor-image',
  indent: 'EditorTheme-indent',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'EditorTheme-layoutContainer',
  layoutItem: 'EditorTheme-layoutItem',
  link: 'EditorTheme-link',
  list: {
    checklist: 'EditorTheme-checklist',
    listitem: 'EditorTheme-listItem',
    listitemChecked: 'EditorTheme-listItemChecked',
    listitemUnchecked: 'EditorTheme-listItemUnchecked',
    nested: {
      listitem: 'EditorTheme-nestedListItem',
    },
    olDepth: ['EditorTheme-ol1', 'EditorTheme-ol2', 'EditorTheme-ol3', 'EditorTheme-ol4', 'EditorTheme-ol5'],
    ul: 'EditorTheme-ul',
  },
  ltr: 'EditorTheme-ltr',
  mark: 'EditorTheme-mark',
  markOverlap: 'EditorTheme-markOverlap',
  paragraph: 'EditorTheme-paragraph',
  quote: 'EditorTheme-quote',
  rtl: 'EditorTheme-rtl',
  specialText: 'EditorTheme-specialText',
  tab: 'EditorTheme-tabNode',
  table: 'EditorTheme-table',
  tableAddColumns: 'EditorTheme-tableAddColumns',
  tableAddRows: 'EditorTheme-tableAddRows',
  tableAlignment: {
    center: 'EditorTheme-tableAlignmentCenter',
    right: 'EditorTheme-tableAlignmentRight',
  },
  tableCell: 'EditorTheme-tableCell',
  tableCellActionButton: 'EditorTheme-tableCellActionButton',
  tableCellActionButtonContainer: 'EditorTheme-tableCellActionButtonContainer',
  tableCellHeader: 'EditorTheme-tableCellHeader',
  tableCellResizer: 'EditorTheme-tableCellResizer',
  tableCellSelected: 'EditorTheme-tableCellSelected',
  tableFrozenColumn: 'EditorTheme-tableFrozenColumn',
  tableFrozenRow: 'EditorTheme-tableFrozenRow',
  tableRowStriping: 'EditorTheme-tableRowStriping',
  tableScrollableWrapper: 'EditorTheme-tableScrollableWrapper',
  tableSelected: 'EditorTheme-tableSelected',
  tableSelection: 'EditorTheme-tableSelection',
  text: {
    bold: 'EditorTheme-textBold',
    capitalize: 'EditorTheme-textCapitalize',
    code: 'EditorTheme-textCode',
    highlight: 'EditorTheme-textHighlight',
    italic: 'EditorTheme-textItalic',
    lowercase: 'EditorTheme-textLowercase',
    strikethrough: 'EditorTheme-textStrikethrough',
    subscript: 'EditorTheme-textSubscript',
    superscript: 'EditorTheme-textSuperscript',
    underline: 'EditorTheme-textUnderline',
    underlineStrikethrough: 'EditorTheme-textUnderlineStrikethrough',
    uppercase: 'EditorTheme-textUppercase',
  },
};

export default editorTheme;
